Repository PdxCodeGuild/class_HB2, pull requests merged in 2022-08, with the labels that each got.

#212 Jonpan django lab01
  code/jonpan/django/lab01/manage.py
  code/jonpan/django/lab01/myapp/__init__.py
  code/jonpan/django/lab01/myapp/admin.py
  code/jonpan/django/lab01/myapp/apps.py
  code/jonpan/django/lab01/myapp/models.py
  code/jonpan/django/lab01/myapp/templates/myapp/mytemplate.html
  code/jonpan/django/lab01/myapp/tests.py
  code/jonpan/django/lab01/myapp/urls.py
  code/jonpan/django/lab01/myapp/views.py
  code/jonpan/django/lab01/myproject/__init__.py
  code/jonpan/django/lab01/myproject/asgi.py
  code/jonpan/django/lab01/myproject/settings.py
  code/jonpan/django/lab01/myproject/urls.py
  code/jonpan/django/lab01/myproject/wsgi.py
Labels: Review Complete

#206 burrito form completed
  code/matt/html_css_flask/lab04_burrito_form/lab-04.css
  code/matt/html_css_flask/lab04_burrito_form/lab-04.html
Labels: Changes Requested

#209 Muki company landing
  code/muki/HTML/template/fika.html
  code/muki/other/copy_snake_code.py
Labels: Review Complete

#220 Kelin lab01 todo
  code/kelin/labs/django_labs/lab01_todo/manage.py
  code/kelin/labs/django_labs/lab01_todo/myapp/__init__.py
  code/kelin/labs/django_labs/lab01_todo/myapp/admin.py
  code/kelin/labs/django_labs/lab01_todo/myapp/apps.py
  code/kelin/labs/django_labs/lab01_todo/myapp/migrations/0001_initial.py
  code/kelin/labs/django_labs/lab01_todo/myapp/migrations/0002_priority_todoitem.py
  code/kelin/labs/django_labs/lab01_todo/myapp/migrations/0003_delete_mymodel_alter_priority_name.py
  code/kelin/labs/django_labs/lab01_todo/myapp/migrations/0004_alter_priority_name.py
  code/kelin/labs/django_labs/lab01_todo/myapp/migrations/__init__.py
  code/kelin/labs/django_labs/lab01_todo/myapp/models.py
  code/kelin/labs/django_labs/lab01_todo/myapp/templates/myapp/todo.html
  code/kelin/labs/django_labs/lab01_todo/myapp/tests.py
  code/kelin/labs/django_labs/lab01_todo/myapp/urls.py
  code/kelin/labs/django_labs/lab01_todo/myapp/views.py
  code/kelin/labs/django_labs/lab01_todo/todo/__init__.py
  code/kelin/labs/django_labs/lab01_todo/todo/asgi.py
  code/kelin/labs/django_labs/lab01_todo/todo/settings.py
  code/kelin/labs/django_labs/lab01_todo/todo/urls.py
  code/kelin/labs/django_labs/lab01_todo/todo/wsgi.py
  code/kelin/labs/django_labs/manage.py
  code/kelin/labs/django_labs/polls/__init__.py
  code/kelin/labs/django_labs/polls/admin.py
  code/kelin/labs/django_labs/polls/apps.py
  code/kelin/labs/django_labs/polls/migrations/0001_initial.py
  code/kelin/labs/django_labs/polls/migrations/__init__.py
  code/kelin/labs/django_labs/polls/models.py
  code/kelin/labs/django_labs/polls/tests.py
  code/kelin/labs/django_labs/polls/urls.py
  code/kelin/labs/django_labs/polls/views.py
  code/kelin/labs/django_labs/pollsproject/__init__.py
  code/kelin/labs/django_labs/pollsproject/asgi.py
  code/kelin/labs/django_labs/pollsproject/settings.py
  code/kelin/labs/django_labs/pollsproject/urls.py
  code/kelin/labs/django_labs/pollsproject/wsgi.py
Labels: Reviewing

#221 lab01 complete
  code/daniel/django_files/django-lab01-to_do/ToDo/__init__.py
  code/daniel/django_files/django-lab01-to_do/ToDo/admin.py
  code/daniel/django_files/django-lab01-to_do/ToDo/apps.py
  code/daniel/django_files/django-lab01-to_do/ToDo/models.py
  code/daniel/django_files/django-lab01-to_do/ToDo/templates/ToDo/mytemplate.html
  code/daniel/django_files/django-lab01-to_do/ToDo/tests.py
  code/daniel/django_files/django-lab01-to_do/ToDo/urls.py
  code/daniel/django_files/django-lab01-to_do/ToDo/views.py
  code/daniel/django_files/django-lab01-to_do/lab01/__init__.py
  code/daniel/django_files/django-lab01-to_do/lab01/asgi.py
  code/daniel/django_files/django-lab01-to_do/lab01/settings.py
  code/daniel/django_files/django-lab01-to_do/lab01/urls.py
  code/daniel/django_files/django-lab01-to_do/lab01/wsgi.py
  code/daniel/django_files/django-lab01-to_do/manage.py
Labels: Review Complete

#222 Zach lab06 flask
  code/zach/html-labs/lab06-flask/Example/flask-example.py
  code/zach/html-labs/lab06-flask/Example/template/index.html
  code/zach/html-labs/lab06-flask/Example/template/sum.html
  code/zach/html-labs/lab06-flask/lab06-flask.py
  code/zach/html-labs/lab06-flask/templates/index.html
  code/zach/html-labs/lab06-flask/templates/password.html
Labels: Reviewing

#207 lab06 flask redo complete
  code/matt/html_css_flask/lab06_flask_redo_unit_converter/app.py
  code/matt/html_css_flask/lab06_flask_redo_unit_converter/template/index.html
Labels: Changes Requested, Reviewing

#217 Justin django lab01
  code/justin/Django/django_lab01/Lab01/Lab01/asgi.py
  code/justin/Django/django_lab01/Lab01/Lab01/settings.py
  code/justin/Django/django_lab01/Lab01/Lab01/urls.py
  code/justin/Django/django_lab01/Lab01/Lab01/wsgi.py
  code/justin/Django/django_lab01/Lab01/manage.py
  code/justin/Django/django_lab01/Lab01/todo/__init__.py
  code/justin/Django/django_lab01/Lab01/todo/admin.py
  code/justin/Django/django_lab01/Lab01/todo/apps.py
  code/justin/Django/django_lab01/Lab01/todo/forms.py
  code/justin/Django/django_lab01/Lab01/todo/migrations/0001_initial.py
  code/justin/Django/django_lab01/Lab01/todo/migrations/0002_todoitem.py
  code/justin/Django/django_lab01/Lab01/todo/migrations/0003_todoitem_date_created_alter_priority_name.py
  code/justin/Django/django_lab01/Lab01/todo/migrations/0004_alter_todoitem_date_created.py
  code/justin/Django/django_lab01/Lab01/todo/migrations/0005_alter_priority_name_alter_todoitem_date_created.py
  code/justin/Django/django_lab01/Lab01/todo/migrations/0006_alter_todoitem_date_created.py
  code/justin/Django/django_lab01/Lab01/todo/migrations/0007_alter_todoitem_date_created.py
  code/justin/Django/django_lab01/Lab01/todo/migrations/__init__.py
  code/justin/Django/django_lab01/Lab01/todo/models.py
  code/justin/Django/django_lab01/Lab01/todo/templates/todo/index.html
  code/justin/Django/django_lab01/Lab01/todo/tests.py
  code/justin/Django/django_lab01/Lab01/todo/urls.py
  code/justin/Django/django_lab01/Lab01/todo/views.py
  code/justin/Django/forms_lab/formapp/urls.py
  code/justin/Django/practice_lab/lab01/__init__.py
  code/justin/Django/practice_lab/lab01/asgi.py
  code/justin/Django/practice_lab/lab01/settings.py
  code/justin/Django/practice_lab/lab01/urls.py
  code/justin/Django/practice_lab/lab01/wsgi.py
  code/justin/Django/practice_lab/labapp/__init__.py
  code/justin/Django/practice_lab/labapp/admin.py
  code/justin/Django/practice_lab/labapp/apps.py
  code/justin/Django/practice_lab/labapp/forms.py
  code/justin/Django/practice_lab/labapp/migrations/0001_initial.py
  code/justin/Django/practice_lab/labapp/migrations/0002_todo.py
  code/justin/Django/practice_lab/labapp/migrations/0003_alter_todo_importance.py
  code/justin/Django/practice_lab/labapp/migrations/0004_alter_todo_importance.py
  code/justin/Django/practice_lab/labapp/migrations/0005_todo_completed_date.py
  code/justin/Django/practice_lab/labapp/migrations/0006_alter_todo_importance.py
  code/justin/Django/practice_lab/labapp/migrations/0007_alter_todo_importance.py
  code/justin/Django/practice_lab/labapp/migrations/0008_alter_todo_importance.py
  code/justin/Django/practice_lab/labapp/migrations/0009_alter_todo_importance.py
  code/justin/Django/practice_lab/labapp/migrations/0010_alter_todo_importance.py
  code/justin/Django/practice_lab/labapp/migrations/0011_alter_todo_importance.py
  code/justin/Django/practice_lab/labapp/migrations/__init__.py
  code/justin/Django/practice_lab/labapp/models.py
  code/justin/Django/practice_lab/labapp/templates/labapp/close.html
  code/justin/Django/practice_lab/labapp/templates/labapp/todo.html
  code/justin/Django/practice_lab/labapp/tests.py
  code/justin/Django/practice_lab/labapp/urls.py
  code/justin/Django/practice_lab/labapp/views.py
  code/justin/Django/practice_lab/manage.py
  code/justin/Python/contacts.csv
Labels: Review Complete

#226 Justin django lab05
  code/justin/Django/django_lab05/blog/__init__.py
  code/justin/Django/django_lab05/blog/admin.py
  code/justin/Django/django_lab05/blog/apps.py
  code/justin/Django/django_lab05/blog/forms.py
  code/justin/Django/django_lab05/blog/migrations/0001_initial.py
  code/justin/Django/django_lab05/blog/migrations/__init__.py
  code/justin/Django/django_lab05/blog/models.py
  code/justin/Django/django_lab05/blog/templates/blog/create.html
  code/justin/Django/django_lab05/blog/templates/blog/login.html
  code/justin/Django/django_lab05/blog/templates/blog/profile.html
  code/justin/Django/django_lab05/blog/templates/blog/register.html
  code/justin/Django/django_lab05/blog/tests.py
  code/justin/Django/django_lab05/blog/urls.py
  code/justin/Django/django_lab05/blog/views.py
  code/justin/Django/django_lab05/lab05/__init__.py
  code/justin/Django/django_lab05/lab05/asgi.py
  code/justin/Django/django_lab05/lab05/settings.py
  code/justin/Django/django_lab05/lab05/urls.py
  code/justin/Django/django_lab05/lab05/wsgi.py
  code/justin/Django/django_lab05/manage.py
Labels: Review Complete
