Repository PdxCodeGuild/class_HB2, pull requests merged in 2022-09, with the labels that each got.

#227 Jonpan - django lab05
  code/jonpan/django/lab05/manage.py
  code/jonpan/django/lab05/myapp/__init__.py
  code/jonpan/django/lab05/myapp/admin.py
  code/jonpan/django/lab05/myapp/apps.py
  code/jonpan/django/lab05/myapp/migrations/0001_initial.py
  code/jonpan/django/lab05/myapp/migrations/0002_alter_blogpost_options_alter_blogpost_user.py
  code/jonpan/django/lab05/myapp/migrations/__init__.py
  code/jonpan/django/lab05/myapp/models.py
  code/jonpan/django/lab05/myapp/templates/base.html
  code/jonpan/django/lab05/myapp/templates/index.html
  code/jonpan/django/lab05/myapp/templates/myapp/blogpost.html
  code/jonpan/django/lab05/myapp/templates/myapp/create.html
  code/jonpan/django/lab05/myapp/templates/myapp/login.html
  code/jonpan/django/lab05/myapp/templates/myapp/profile.html
  code/jonpan/django/lab05/myapp/templates/myapp/register.html
  code/jonpan/django/lab05/myapp/tests.py
  code/jonpan/django/lab05/myapp/urls.py
  code/jonpan/django/lab05/myapp/views.py
  code/jonpan/django/lab05/myproject/__init__.py
  code/jonpan/django/lab05/myproject/asgi.py
  code/jonpan/django/lab05/myproject/settings.py
  code/jonpan/django/lab05/myproject/urls.py
  code/jonpan/django/lab05/myproject/wsgi.py
Labels: Review Complete

#216 Lab01 todo
  code/matt/django/lab01/todo/manage.py
  code/matt/django/lab01/todo/polls/__init__.py
  code/matt/django/lab01/todo/polls/admin.py
  code/matt/django/lab01/todo/polls/apps.py
  code/matt/django/lab01/todo/polls/models.py
  code/matt/django/lab01/todo/polls/templates/polls/index.html
  code/matt/django/lab01/todo/polls/templates/polls/todoitem_form.html
  code/matt/django/lab01/todo/polls/tests.py
  code/matt/django/lab01/todo/polls/urls.py
  code/matt/django/lab01/todo/polls/views.py
  code/matt/django/lab01/todo/todo/__init__.py
  code/matt/django/lab01/todo/todo/asgi.py
  code/matt/django/lab01/todo/todo/settings.py
  code/matt/django/lab01/todo/todo/urls.py
  code/matt/django/lab01/todo/todo/wsgi.py
Labels: Changes Requested, Reviewing

#238 Daniel django lab05 blog
  code/daniel/django_files/lab05-blog/Pipfile
  code/daniel/django_files/lab05-blog/Pipfile.lock
  code/daniel/django_files/lab05-blog/blog_app/__init__.py
  code/daniel/django_files/lab05-blog/blog_app/admin.py
  code/daniel/django_files/lab05-blog/blog_app/apps.py
  code/daniel/django_files/lab05-blog/blog_app/models.py
  code/daniel/django_files/lab05-blog/blog_app/templates/blog_app/index.html
  code/daniel/django_files/lab05-blog/blog_app/templates/blog_app/login.html
  code/daniel/django_files/lab05-blog/blog_app/templates/blog_app/profile.html
  code/daniel/django_files/lab05-blog/blog_app/templates/blog_app/register.html
  code/daniel/django_files/lab05-blog/blog_app/tests.py
  code/daniel/django_files/lab05-blog/blog_app/urls.py
  code/daniel/django_files/lab05-blog/blog_app/views.py
  code/daniel/django_files/lab05-blog/blog_project/__init__.py
  code/daniel/django_files/lab05-blog/blog_project/asgi.py
  code/daniel/django_files/lab05-blog/blog_project/settings.py
  code/daniel/django_files/lab05-blog/blog_project/urls.py
  code/daniel/django_files/lab05-blog/blog_project/wsgi.py
  code/daniel/django_files/lab05-blog/manage.py
Labels: Reviewing

#239 Zach lab02 blog
  code/zach/Django/lab02-blog/accounts/__init__.py
  code/zach/Django/lab02-blog/accounts/admin.py
  code/zach/Django/lab02-blog/accounts/apps.py
  code/zach/Django/lab02-blog/accounts/migrations/__init__.py
  code/zach/Django/lab02-blog/accounts/models.py
  code/zach/Django/lab02-blog/accounts/tests.py
  code/zach/Django/lab02-blog/accounts/urls.py
  code/zach/Django/lab02-blog/accounts/views.py
  code/zach/Django/lab02-blog/blog_app/__init__.py
  code/zach/Django/lab02-blog/blog_app/admin.py
  code/zach/Django/lab02-blog/blog_app/apps.py
  code/zach/Django/lab02-blog/blog_app/migrations/0001_initial.py
  code/zach/Django/lab02-blog/blog_app/migrations/0002_blogpost_body_alter_blogpost_public.py
  code/zach/Django/lab02-blog/blog_app/migrations/__init__.py
  code/zach/Django/lab02-blog/blog_app/models.py
  code/zach/Django/lab02-blog/blog_app/tests.py
  code/zach/Django/lab02-blog/blog_app/urls.py
  code/zach/Django/lab02-blog/blog_app/views.py
  code/zach/Django/lab02-blog/blog_project/__init__.py
  code/zach/Django/lab02-blog/blog_project/asgi.py
  code/zach/Django/lab02-blog/blog_project/settings.py
  code/zach/Django/lab02-blog/blog_project/urls.py
  code/zach/Django/lab02-blog/blog_project/wsgi.py
  code/zach/Django/lab02-blog/manage.py
  code/zach/Django/lab02-blog/templates/base.html
  code/zach/Django/lab02-blog/templates/index.html
  code/zach/Django/lab02-blog/templates/registration/login.html
  code/zach/Django/lab02-blog/templates/registration/profile.html
  code/zach/Django/lab02-blog/templates/registration/register.html
Labels: Reviewing

#241 Kelin lab01 jsredo
  code/kelin/labs/javascript/lab01_redo/average_numbers_redo.js
  code/kelin/labs/javascript/lab01_redo/index.html
Labels: Reviewing

#242 Jonpan js lab01
  code/jonpan/js/lab01/app.js
  code/jonpan/js/lab01/index.html
  code/jonpan/js/lab01/v2/app.js
  code/jonpan/js/lab01/v2/index.html
  code/jonpan/test/test.txt
Labels: Reviewing

#243 Justin java lab01
  code/justin/Java/Lab01/Number to Phrase/num.html
  code/justin/Java/Lab01/Number to Phrase/num.js
  code/justin/Java/Lab01/Unit Converter/lab01.html
  code/justin/Java/Lab01/Unit Converter/lab01.js
Labels: Reviewing

#240 Completed version 1 of the javascript lab.
  code/zach/javascript/lab01_average_numbers/index.html
  code/zach/javascript/lab01_average_numbers/lab01_average_numbers.js
Labels: Reviewing

#250 Zach lab02 weather api
  code/zach/javascript/lab02-weather-api/.gitignore
  code/zach/javascript/lab02-weather-api/index.html
  code/zach/javascript/lab02-weather-api/weather_api.js
Labels: Review Complete

#251 Justin java api
  code/justin/Java/Lab02/api/.gitignore
  code/justin/Java/Lab02/api/weather.html
  code/justin/Java/Lab02/api/weather.js
Labels: Review Complete

#253 Matt weather app
  code/matt/lab02/.gitignore
  code/matt/lab02/lab07-weather_api.html
  code/matt/lab02/weather.js
Labels: Review Complete

#254 Andy lab07 javascript weather ready for review
  code/Andy/javascript/weather_api/.gitignore
  code/Andy/javascript/weather_api/app.js
  code/Andy/javascript/weather_api/styles.css
  code/Andy/javascript/weather_api/weather_api.html
Labels: Review Complete

#256 Kelin lab weatherapi
  code/kelin/labs/javascript/weather_api/.gitignore
  code/kelin/labs/javascript/weather_api/app_connect.js
  code/kelin/labs/javascript/weather_api/index.html
  code/kelin/labs/javascript/weather_api/secrets.js
Labels: Reviewing

#257 Jonpan JS Weather API Lab
  code/jonpan/js/lab02/app.js
  code/jonpan/js/lab02/index.html
Labels: Review Complete

#258 Daniel js lab02 weather api
  code/daniel/js_files/daniel-weatherAPI/.gitignore
  code/daniel/js_files/daniel-weatherAPI/index.html
  code/daniel/js_files/daniel-weatherAPI/weatherAPI.js
Labels: Changes Requested

#249 Daniel js lab01 avg num
  code/daniel/js_files/daniel-avgNum/angNum.js
  code/daniel/js_files/daniel-avgNum/index.html
Labels: Changes Requested

#252 Andy lab01 javascript redo ready for review
  code/Andy/javascript/lab_redo/index.html
  code/Andy/javascript/lab_redo/redo.js
  code/Andy/javascript/lab_redo/style.css
Labels: Review Complete

#259 Justin java cal
  code/justin/Java/Lab02/api/secrets.js
  code/justin/Java/Lab03/cal.js
  code/justin/Java/Lab03/calculator.css
  code/justin/Java/Lab03/calculator.html
Labels: Review Complete

#261 Kelin lab calculator
  code/kelin/labs/javascript/calculator/calculations.js
  code/kelin/labs/javascript/calculator/calculator.css
  code/kelin/labs/javascript/calculator/calculator.html
Labels: Review Complete

#262 Zach lab03 calculator
  code/zach/javascript/lab02-weather-api/secrets.js
  code/zach/javascript/lab03-calculator/calculator.css
  code/zach/javascript/lab03-calculator/calculator.html
  code/zach/javascript/lab03-calculator/calculator.js
Labels: Review Complete

#260 Jonpan js lab04 - Vue Redo
  code/jonpan/js/lab04/index.html
Labels: Review Complete

#264 Jonpan submitting lab 03 - calculator
  code/jonpan/js/lab03/app.js
  code/jonpan/js/lab03/calculator.css
  code/jonpan/js/lab03/index.html
Labels: Review Complete

#267 Matt lab01 redo js
  code/matt/javascript/lab01_javascript_redo/index.html
  code/matt/javascript/lab01_javascript_redo/redo.js
Labels: Review Complete
